import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";

export default function Home() {
  return (
    // <div className={`${styles.container} ${styles1.body}`}>
    <div className={styles.container}>
      <Head>
        <title>Hunting Coders </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={`${styles.title}`}>Blogs for Beginners</h1>
        <p className={styles.description}>
          Starting Coding with Shahabuddin Ahmed and Bright your future
        </p>
      </main>
      <div className={styles.myimg}>
        <Image
          src="/myimg.png"
          height={225}
          width={225}
        />
      </div>
      <div className={styles.grid}>
        <a href="/blogposts/for-students" className={styles.card}>
          <h2>For Students &rarr;</h2>
          <p>Keep it Up and make them powerfully web developer and learn more skills</p>
        </a>

        <a href="/blogposts/for-developer" className={styles.card}>
          <h2>For Developer &rarr;</h2>
          <p>You have a degree is deos`nt matter, just yoy have any skill</p>
        </a>

        <a href="/blogposts/for-builder" className={styles.card}>
          <h2>For Builder &rarr;</h2>
          <p>Discover and deploy boilerplate example Next.js projects. ANd doing best</p>
        </a>

        <a href="/blogposts/for-teacher" className={styles.card}>
          <h2>For Teacher &rarr;</h2>
          <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
        </a>
      </div>
    </div>
  );
}
